language: python
python:
        - "3.5"
        - "3.6"
install: 
        - pip install coveralls
script:
        - python3 -m unittest
        - coverage run --source cookiecutter rpn.py test
after_success:
        coveralls
